export const FETCH_PHOTOS_REQUEST = "FETCH_PHOTOS_REQUEST";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAILURE = "FETCH_PHOTOS_FAILURE";

export const FETCH_FILTER_PHOTOS_REQUEST = "FETCH_FILTER_PHOTOS_REQUEST";
export const FETCH_FILTER_PHOTOS_SUCCESS = "FETCH_FILTER_PHOTOS_SUCCESS";
export const FETCH_FILTER_PHOTOS_FAILURE = "FETCH_FILTER_PHOTOS_FAILURE";

export const FETCH_ALBUMS_REQUEST = "FETCH_ALBUMS_REQUEST";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";
export const FETCH_ALBUMS_FAILURE = "FETCH_ALBUMS_FAILURE";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const FILTER_BY_ALBUM = "FILTER_BY_ALBUM";

export const SEARCH_BY_PHOTO = "SEARCH_BY_PHOTO";
